services:
  chat-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: chat-api
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: qdrant
    ports:
      - "6333:6333"  # API HTTP
      - "6334:6334"  # API gRPC (opcional)
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage:
